global:
 resolve_timeout: 1m

templates:
  - '/etc/alertmanager/*.tmpl'

receivers:
 - name: 'team-ops'
   telegram_configs:
    - chat_id: -1001834957574
      bot_token: 6205605582:AAFpJVjpY7qX2HmSPCq2n-szcIbwbwQ8ORI
      api_url: https://api.telegram.org
      send_resolved: true
      #parse_mode: ''
      #message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"


 - name: 'team-dev'
   telegram_configs:
    - chat_id: -1001831885845
      bot_token: 6205605582:AAFpJVjpY7qX2HmSPCq2n-szcIbwbwQ8ORI
      api_url: https://api.telegram.org
      send_resolved: true
      #parse_mode: ''
      #message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"


 - name: 'team-support'
   telegram_configs:
    - chat_id: -1001732114247
      bot_token: 6205605582:AAFpJVjpY7qX2HmSPCq2n-szcIbwbwQ8ORI
      api_url: https://api.telegram.org
      send_resolved: true
      #parse_mode: ''
      #message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"


      
route:
 group_by: ['alertname','env'] 
 group_wait: 15s
 group_interval: 2m
 repeat_interval: 4h
 receiver: team-support
 routes:
    - matchers:
      - env="infra"
      group_by: [severity]
      routes:
        - receiver: team-ops
          matchers:
          - severity="critical"
          continue: true
        - receiver: team-support
          matchers:
          - severity=~ warning|critical
          

    - matchers:
      - env="http-probe-frontend"
      group_by: [severity]
      routes:
        - receiver: team-ops
          matchers:
          - severity="critical"
          continue: true
        - receiver: team-support
          matchers:
          - severity=~ warning|critical
          continue: true
        - receiver: team-dev
          matchers:
          - severity="warning"