filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.ilm.overwrite: true

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

setup.dashboards.enabled: true


output.elasticsearch:
  hosts: ["${ELASTIC_HOSTS}"]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"

processors:
- add_docker_metadata: ~

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

