---
version: '3.1'
services:
  wordpress:
    image: wordpress:php8.0-fpm
    networks:
      back:
        aliases:
          - wordpress
      front:
        aliases:
          - wordpress-front
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    networks:
      back:
        aliases:
          - mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/00_schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro

  nginx:
    image: nginx:1.23.0
    networks:
      back:
        aliases:
          - local.test
      front:
        aliases:
          - nginx
    ports:
      - "443:443"
      - "80:80"
      - "9090:9090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wordpress:/var/www/html
      - .htpasswd:/etc/nginx/.htpasswd
      - ./server.key:/etc/nginx/keys/server.key
      - ./server.crt:/etc/nginx/keys/server.crt
    depends_on:
      - wordpress
      - prometheus
  


  prometheus:
    image: prom/prometheus:v2.44.0
    networks:
      back:
        aliases:
          - prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always


  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      back:
          aliases:
            - node-exporter
    restart: always


  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter:latest
    command:
    - '--config.my-cnf=/mysqld-exporter/exporter.cnf'
    networks:
      back:
          aliases:
            - mysqld-exporter
    volumes:
      - ./mysqld-exporter:/mysqld-exporter
    restart: always
    depends_on:
      - mysql

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    environment:
      SSL_VERIFY: false
    command:
    - '-nginx.scrape-uri=https://local.test:443/nginx_status'
    - '-web.telemetry-path=/metrics'
    networks:
      back:
          aliases:
            - nginx-exporter
    depends_on:
      - nginx

  blackbox-exporter:
    image: prom/blackbox-exporter
    restart: always
    command:
    - '--config.file=/blackbox/config.yml'
    volumes:
      - ./blackbox/config.yml:/blackbox/config.yml
    networks:
      back:
        aliases:
            - blackbox-exporter


  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      back:
          aliases:
            - cadvisor
    restart: always
 
  wp-exporter:
    image: ghcr.io/aorfanos/wordpress-exporter/wordpress-exporter:v0.0.8
    networks:
      back:
          aliases:
            - wp-exporter
    ports:
      - "11011:11011"
    command: -auth.user admin -auth.pass cc1cc2CC3 -host http://local.test -auth.basic true  

  grafana:
    image: grafana/grafana:9.5.0-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      back:
        aliases:
          - grafana
      front:
    ports:
      - "3000:3000"
    restart: always

networks:
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
    internal: true

  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
    

volumes:
  mysql_data:
  grafana_data:
