---
version: '3.1'
services:
  wordpress:
    image: wordpress:php8.0-fpm
    networks:
      back:
        aliases:
          - wordpress
      front:
        aliases:
          - wordpress-front
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    networks:
      back:
        aliases:
          - mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/00_schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro

  nginx:
    image: nginx:1.23.0
    container_name: nginx
    networks:
      back:
        aliases:
          - local.test
      front:
        aliases:
          - nginx
    ports:
      - "443:443"
      - "80:80"
      - "9090:9090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wordpress:/var/www/html
      - .htpasswd:/etc/nginx/.htpasswd
      - ./server.key:/etc/nginx/keys/server.key
      - ./server.crt:/etc/nginx/keys/server.crt
    depends_on:
      - wordpress
      - prometheus
  


  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    networks:
      back:
        aliases:
          - prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules_alert.yml:/etc/prometheus/rules_alert.yml:ro
      #- ./prometheus/promdata:/prometheus/data
    command:
      #- '--storage.tsdb.path=/prometheus/data'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always


  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      back:
          aliases:
            - node-exporter
    restart: always


  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter:latest
    container_name: mysqld-exporter
    command:
    - '--config.my-cnf=/mysqld-exporter/exporter.cnf'
    networks:
      back:
          aliases:
            - mysqld-exporter
    volumes:
      - ./mysqld-exporter:/mysqld-exporter
    restart: always
    depends_on:
      - mysql

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx-exporter
    environment:
      SSL_VERIFY: false
    command:
    - '-nginx.scrape-uri=https://local.test:443/nginx_status'
    - '-web.telemetry-path=/metrics'
    networks:
      back:
          aliases:
            - nginx-exporter
    depends_on:
      - nginx

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: always
    command:
    - '--config.file=/blackbox/config.yml'
    volumes:
      - ./blackbox/config.yml:/blackbox/config.yml
    networks:
      back:
        aliases:
            - blackbox-exporter


  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      back:
          aliases:
            - cadvisor
    restart: always
 
  wp-exporter:
    image: ghcr.io/aorfanos/wordpress-exporter/wordpress-exporter:v0.0.8
    container_name: wp-exporter
    networks:
      back:
          aliases:
            - wp-exporter
    ports:
      - "11011:11011"
    command: -auth.user admin -auth.pass cc1cc2CC3 -host http://local.test -auth.basic true  

  grafana:
    image: grafana/grafana:9.5.0-ubuntu
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      back:
        aliases:
          - grafana
      front:
    ports:
      - "3000:3000"
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/data:/var/lib/alertmanager/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/var/lib/alertmanager/data'
    ports:
      - '9093:9093'
    networks:
      front:
      back:
        aliases:
          - alertmanager


  vmstorage-1:
    container_name: vmstorage-1
    image: victoriametrics/vmstorage:v1.94.0-cluster
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-1:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=2w'
    restart: always
    networks:
      back:
  vmstorage-2:
    container_name: vmstorage-2
    image: victoriametrics/vmstorage:v1.94.0-cluster
    ports:
      - 8482       
      - 8400        
      - 8401
    volumes:
      - strgdata-2:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=2w'
    restart: always
    networks:
      back:

  vminsert:
    container_name: vminsert
    image: victoriametrics/vminsert:v1.94.0-cluster
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - '--storageNode=vmstorage-1:8400'
      - '--storageNode=vmstorage-2:8400'
    ports:
      - 8480
    restart: always
    networks:
      back:

  vmselect-1:
    container_name: vmselect-1
    image: victoriametrics/vmselect:v1.94.0-cluster
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - '--storageNode=vmstorage-1:8401'
      - '--storageNode=vmstorage-2:8401'
    ports:
      - 8481
    restart: always
    networks:
      back:
  vmselect-2:
    container_name: vmselect-2
    image: victoriametrics/vmselect:v1.94.0-cluster
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - '--storageNode=vmstorage-1:8401'
      - '--storageNode=vmstorage-2:8401'
    ports:
      - 8481
    restart: always
    networks:
      back:
  
  vmauth:
    container_name: vmauth
    image: victoriametrics/vmauth:v1.94.0
    depends_on:
      - "vmselect-1"
      - "vmselect-2"
    volumes:
      - ./auth-cluster.yml:/etc/auth.yml
#      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--auth.config=/etc/auth.yml'
    ports:
      - 8427:8427
    restart: always
    networks:
      back:
      front:

networks:
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
    internal: true

  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
    

volumes:
  mysql_data:
  grafana_data:
  strgdata-1: 
  strgdata-2: 
