global:
  scrape_interval: 5s
  external_labels:
      monitor: 'otus-dz'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - target_label: instance
        replacement: prometheus-server

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mysqld'
    static_configs:
      - targets: ['mysqld-exporter:9104']
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  
  - job_name: 'alertmanagers'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_wordpress]
    static_configs:
      - targets:
        - https://local.test:443/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: instance
        replacement: wordpress

  - job_name: wordpress_exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['wp-exporter:11011']

rule_files:
  - /etc/prometheus/rules_alert.yml

alerting:
  alertmanagers:
    - static_configs: 
       - targets: 
          - 'alertmanager:9093'

  